version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGODB_URI=mongodb://mongo:27017/SecureSharing
      - ACCESS_TOKEN_SECRET=your-super-secure-jwt-secret-key-change-this-in-production
    depends_on:
      - mongo
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=SecureSharing

volumes:
  mongo_data:
  uploads:
